### ISSUE TITLE
Import แล้ว แต่ IDE ขึ้นหาไม่เจอ

### ISSUE THREAD

**Issue by ghost** [DrowningToast/bloodalert#11]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/112678792/207054452-bb9f16ec-bb7e-475f-a0f3-7c2f341f5cf0.png">
 
import ไฟล์ Test.py แล้ว แต่ IDE ขึ้นหาไม่เจอ รบกวนพูช่วยสำรวจเพิ่มเติมที เดี๋ยวเรา refactor code ส่วนอื่นให้

**Comment by DrowningToast** [comment]
Fixed in the 7bdecbd9

edit: typo
